// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

package libhuestacean

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A room contains a bunch of devices with given spatial location
type Room struct {
	// The name of this room
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Devices contained within this room, along with their location
	Devices              map[uint32]*DeviceLocation `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_5d41ab01a39355f8, []int{0}
}
func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (dst *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(dst, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Room) GetDevices() map[uint32]*DeviceLocation {
	if m != nil {
		return m.Devices
	}
	return nil
}

func init() {
	proto.RegisterType((*Room)(nil), "libhuestacean.Room")
	proto.RegisterMapType((map[uint32]*DeviceLocation)(nil), "libhuestacean.Room.DevicesEntry")
}

func init() { proto.RegisterFile("room.proto", fileDescriptor_room_5d41ab01a39355f8) }

var fileDescriptor_room_5d41ab01a39355f8 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xca, 0xcf, 0xcf,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcd, 0xc9, 0x4c, 0xca, 0x28, 0x4d, 0x2d, 0x2e,
	0x49, 0x4c, 0x4e, 0x4d, 0xcc, 0x93, 0xe2, 0x49, 0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0x85, 0x48, 0x2a,
	0x6d, 0x64, 0xe4, 0x62, 0x09, 0xca, 0xcf, 0xcf, 0x15, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d,
	0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xac, 0xb8, 0xd8, 0x21, 0x8a, 0x8b,
	0x25, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0x14, 0xf4, 0x50, 0xcc, 0xd2, 0x03, 0xe9, 0xd4, 0x73,
	0x81, 0x28, 0x71, 0xcd, 0x2b, 0x29, 0xaa, 0x0c, 0x82, 0x69, 0x90, 0x8a, 0xe4, 0xe2, 0x41, 0x96,
	0x10, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x04, 0x1b, 0xcf, 0x1b, 0x04, 0x62, 0x0a, 0x19, 0x73,
	0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x1b, 0xc9, 0xa2, 0x99,
	0x0d, 0xd1, 0xed, 0x93, 0x9f, 0x9c, 0x58, 0x92, 0x99, 0x9f, 0x17, 0x04, 0x51, 0x6b, 0xc5, 0x64,
	0xc1, 0x98, 0xc4, 0x06, 0x76, 0xba, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x8c, 0xdd, 0xfc,
	0xe5, 0x00, 0x00, 0x00,
}
